/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifierCertificatRouteImport } from './routes/verifier-certificat'
import { Route as AppAdministrateursRouteImport } from './routes/_app.administrateurs'
import { Route as AppAvantagesRouteImport } from './routes/_app.avantages'
import { Route as AppCalendrierRouteImport } from './routes/_app.calendrier'
import { Route as AppCoursRouteImport } from './routes/_app.cours'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEvenementsRouteImport } from './routes/_app.evenements'
import { Route as AppFinancesRouteImport } from './routes/_app.finances'
import { Route as AppFormationsRouteImport } from './routes/_app.formations'
import { Route as AppMesCertificatsRouteImport } from './routes/_app.mes-certificats'
import { Route as AppMesFinancesRouteImport } from './routes/_app.mes-finances'
import { Route as AppMonEspaceRouteImport } from './routes/_app.mon-espace'
import { Route as AppMonProfilRouteImport } from './routes/_app.mon-profil'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppPresidenceRouteImport } from './routes/_app.presidence'
import { Route as AppRapportsRouteImport } from './routes/_app.rapports'
import { Route as AppFormationFormationIdRouteImport } from './routes/_app.formation.$formationId'
import { Route as AppMembresIndexRouteImport } from './routes/_app.membres.index'
import { Route as AppMembresMemberIdRouteImport } from './routes/_app.membres.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierCertificatRoute = VerifierCertificatRouteImport.update({
  id: '/verifier-certificat',
  path: '/verifier-certificat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdministrateursRoute = AppAdministrateursRouteImport.update({
  id: '/administrateurs',
  path: '/administrateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppAvantagesRoute = AppAvantagesRouteImport.update({
  id: '/avantages',
  path: '/avantages',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendrierRoute = AppCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursRoute = AppCoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEvenementsRoute = AppEvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppFormationsRoute = AppFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AppRoute,
} as any)
const AppMesCertificatsRoute = AppMesCertificatsRouteImport.update({
  id: '/mes-certificats',
  path: '/mes-certificats',
  getParentRoute: () => AppRoute,
} as any)
const AppMesFinancesRoute = AppMesFinancesRouteImport.update({
  id: '/mes-finances',
  path: '/mes-finances',
  getParentRoute: () => AppRoute,
} as any)
const AppMonEspaceRoute = AppMonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => AppRoute,
} as any)
const AppMonProfilRoute = AppMonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppPresidenceRoute = AppPresidenceRouteImport.update({
  id: '/presidence',
  path: '/presidence',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRoute,
} as any)
const AppFormationFormationIdRoute = AppFormationFormationIdRouteImport.update({
  id: '/formation/$formationId',
  path: '/formation/$formationId',
  getParentRoute: () => AppRoute,
} as any)
const AppMembresIndexRoute = AppMembresIndexRouteImport.update({
  id: '/membres/',
  path: '/membres/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembresMemberIdRoute = AppMembresMemberIdRouteImport.update({
  id: '/membres/$memberId',
  path: '/membres/$memberId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verifier-certificat': typeof VerifierCertificatRoute
  '/administrateurs': typeof AppAdministrateursRoute
  '/avantages': typeof AppAvantagesRoute
  '/calendrier': typeof AppCalendrierRoute
  '/cours': typeof AppCoursRoute
  '/dashboard': typeof AppDashboardRoute
  '/evenements': typeof AppEvenementsRoute
  '/finances': typeof AppFinancesRoute
  '/formations': typeof AppFormationsRoute
  '/mes-certificats': typeof AppMesCertificatsRoute
  '/mes-finances': typeof AppMesFinancesRoute
  '/mon-espace': typeof AppMonEspaceRoute
  '/mon-profil': typeof AppMonProfilRoute
  '/parametres': typeof AppParametresRoute
  '/presidence': typeof AppPresidenceRoute
  '/rapports': typeof AppRapportsRoute
  '/formation/$formationId': typeof AppFormationFormationIdRoute
  '/membres/$memberId': typeof AppMembresMemberIdRoute
  '/membres/': typeof AppMembresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verifier-certificat': typeof VerifierCertificatRoute
  '/administrateurs': typeof AppAdministrateursRoute
  '/avantages': typeof AppAvantagesRoute
  '/calendrier': typeof AppCalendrierRoute
  '/cours': typeof AppCoursRoute
  '/dashboard': typeof AppDashboardRoute
  '/evenements': typeof AppEvenementsRoute
  '/finances': typeof AppFinancesRoute
  '/formations': typeof AppFormationsRoute
  '/mes-certificats': typeof AppMesCertificatsRoute
  '/mes-finances': typeof AppMesFinancesRoute
  '/mon-espace': typeof AppMonEspaceRoute
  '/mon-profil': typeof AppMonProfilRoute
  '/parametres': typeof AppParametresRoute
  '/presidence': typeof AppPresidenceRoute
  '/rapports': typeof AppRapportsRoute
  '/formation/$formationId': typeof AppFormationFormationIdRoute
  '/membres/$memberId': typeof AppMembresMemberIdRoute
  '/membres': typeof AppMembresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verifier-certificat': typeof VerifierCertificatRoute
  '/_app/administrateurs': typeof AppAdministrateursRoute
  '/_app/avantages': typeof AppAvantagesRoute
  '/_app/calendrier': typeof AppCalendrierRoute
  '/_app/cours': typeof AppCoursRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/evenements': typeof AppEvenementsRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/formations': typeof AppFormationsRoute
  '/_app/mes-certificats': typeof AppMesCertificatsRoute
  '/_app/mes-finances': typeof AppMesFinancesRoute
  '/_app/mon-espace': typeof AppMonEspaceRoute
  '/_app/mon-profil': typeof AppMonProfilRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/presidence': typeof AppPresidenceRoute
  '/_app/rapports': typeof AppRapportsRoute
  '/_app/formation/$formationId': typeof AppFormationFormationIdRoute
  '/_app/membres/$memberId': typeof AppMembresMemberIdRoute
  '/_app/membres/': typeof AppMembresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verifier-certificat'
    | '/administrateurs'
    | '/avantages'
    | '/calendrier'
    | '/cours'
    | '/dashboard'
    | '/evenements'
    | '/finances'
    | '/formations'
    | '/mes-certificats'
    | '/mes-finances'
    | '/mon-espace'
    | '/mon-profil'
    | '/parametres'
    | '/presidence'
    | '/rapports'
    | '/formation/$formationId'
    | '/membres/$memberId'
    | '/membres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/verifier-certificat'
    | '/administrateurs'
    | '/avantages'
    | '/calendrier'
    | '/cours'
    | '/dashboard'
    | '/evenements'
    | '/finances'
    | '/formations'
    | '/mes-certificats'
    | '/mes-finances'
    | '/mon-espace'
    | '/mon-profil'
    | '/parametres'
    | '/presidence'
    | '/rapports'
    | '/formation/$formationId'
    | '/membres/$memberId'
    | '/membres'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/verifier-certificat'
    | '/_app/administrateurs'
    | '/_app/avantages'
    | '/_app/calendrier'
    | '/_app/cours'
    | '/_app/dashboard'
    | '/_app/evenements'
    | '/_app/finances'
    | '/_app/formations'
    | '/_app/mes-certificats'
    | '/_app/mes-finances'
    | '/_app/mon-espace'
    | '/_app/mon-profil'
    | '/_app/parametres'
    | '/_app/presidence'
    | '/_app/rapports'
    | '/_app/formation/$formationId'
    | '/_app/membres/$memberId'
    | '/_app/membres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifierCertificatRoute: typeof VerifierCertificatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier-certificat': {
      id: '/verifier-certificat'
      path: '/verifier-certificat'
      fullPath: '/verifier-certificat'
      preLoaderRoute: typeof VerifierCertificatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/administrateurs': {
      id: '/_app/administrateurs'
      path: '/administrateurs'
      fullPath: '/administrateurs'
      preLoaderRoute: typeof AppAdministrateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avantages': {
      id: '/_app/avantages'
      path: '/avantages'
      fullPath: '/avantages'
      preLoaderRoute: typeof AppAvantagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendrier': {
      id: '/_app/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AppCalendrierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cours': {
      id: '/_app/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof AppCoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evenements': {
      id: '/_app/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof AppEvenementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formations': {
      id: '/_app/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof AppFormationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mes-certificats': {
      id: '/_app/mes-certificats'
      path: '/mes-certificats'
      fullPath: '/mes-certificats'
      preLoaderRoute: typeof AppMesCertificatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mes-finances': {
      id: '/_app/mes-finances'
      path: '/mes-finances'
      fullPath: '/mes-finances'
      preLoaderRoute: typeof AppMesFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-espace': {
      id: '/_app/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof AppMonEspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-profil': {
      id: '/_app/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof AppMonProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presidence': {
      id: '/_app/presidence'
      path: '/presidence'
      fullPath: '/presidence'
      preLoaderRoute: typeof AppPresidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports': {
      id: '/_app/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formation/$formationId': {
      id: '/_app/formation/$formationId'
      path: '/formation/$formationId'
      fullPath: '/formation/$formationId'
      preLoaderRoute: typeof AppFormationFormationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membres/': {
      id: '/_app/membres/'
      path: '/membres'
      fullPath: '/membres/'
      preLoaderRoute: typeof AppMembresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membres/$memberId': {
      id: '/_app/membres/$memberId'
      path: '/membres/$memberId'
      fullPath: '/membres/$memberId'
      preLoaderRoute: typeof AppMembresMemberIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdministrateursRoute: typeof AppAdministrateursRoute
  AppAvantagesRoute: typeof AppAvantagesRoute
  AppCalendrierRoute: typeof AppCalendrierRoute
  AppCoursRoute: typeof AppCoursRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEvenementsRoute: typeof AppEvenementsRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppFormationsRoute: typeof AppFormationsRoute
  AppMesCertificatsRoute: typeof AppMesCertificatsRoute
  AppMesFinancesRoute: typeof AppMesFinancesRoute
  AppMonEspaceRoute: typeof AppMonEspaceRoute
  AppMonProfilRoute: typeof AppMonProfilRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPresidenceRoute: typeof AppPresidenceRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppFormationFormationIdRoute: typeof AppFormationFormationIdRoute
  AppMembresMemberIdRoute: typeof AppMembresMemberIdRoute
  AppMembresIndexRoute: typeof AppMembresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministrateursRoute: AppAdministrateursRoute,
  AppAvantagesRoute: AppAvantagesRoute,
  AppCalendrierRoute: AppCalendrierRoute,
  AppCoursRoute: AppCoursRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEvenementsRoute: AppEvenementsRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppFormationsRoute: AppFormationsRoute,
  AppMesCertificatsRoute: AppMesCertificatsRoute,
  AppMesFinancesRoute: AppMesFinancesRoute,
  AppMonEspaceRoute: AppMonEspaceRoute,
  AppMonProfilRoute: AppMonProfilRoute,
  AppParametresRoute: AppParametresRoute,
  AppPresidenceRoute: AppPresidenceRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppFormationFormationIdRoute: AppFormationFormationIdRoute,
  AppMembresMemberIdRoute: AppMembresMemberIdRoute,
  AppMembresIndexRoute: AppMembresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifierCertificatRoute: VerifierCertificatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
